Ext.define('TCPlus.model.WatchListRecord', {
    extend: 'Ext.data.Model',
    fields: [
        {name: fieldStkCode, mapping: fieldStkCode, sortType: 'asUCString'},
        {name: fieldStkName, mapping: fieldStkName, sortType: 'asUCString'},
        {name: fieldStkFName, mapping: fieldStkFName, sortType: 'asUCString'},
        {name: fieldLast, mapping: fieldLast, sortType: 'asFloat'},
        {name: fieldChange, mapping: fieldChange, sortType: 'asFloat'},
        {name: fieldChangePer, mapping: fieldChangePer, sortType: 'asFloat'},
        {name: fieldOpen, mapping: fieldOpen, sortType: 'asFloat'},
        {name: fieldOpenInt, mapping: fieldOpenInt, sortType: 'asFloat'},
        {name: fieldLacp, mapping: fieldLacp, sortType: 'asFloat'},
        {name: fieldPrev, mapping: fieldPrev, sortType: 'asFloat'},
        {name: fieldHigh, mapping: fieldHigh, sortType: 'asFloat'},
        {name: fieldLow, mapping: fieldLow, sortType: 'asFloat'},
        {name: fieldBuy, mapping: fieldBuy, sortType: 'asFloat'},
        {name: fieldSell, mapping: fieldSell, sortType: 'asFloat'},
        {name: fieldBqty, mapping: fieldBqty, sortType: 'asInt'},
        {name: fieldSqty, mapping: fieldSqty, sortType: 'asInt'},
        {name: fieldBuyRate, mapping: fieldBuyRate, sortType: 'asFloat'},
        {name: fieldUnit, mapping: fieldUnit, sortType: 'asInt'},
        {name: fieldVol, mapping: fieldVol, sortType: 'asInt'},
        {name: fieldStkStatus, mapping: fieldStkStatus, sortType: 'asUCString'},
        {name: fieldNews, mapping: fieldNews, sortType: 'asUCString'},
        {name: fieldRSSIndicator, mapping: fieldRSSIndicator, sortType: 'asUCString'},
        {name: fieldTime, mapping: fieldTime, sortType: 'asInt'},
        {name: fieldTotTrade, mapping: fieldTotTrade, sortType: 'asInt'},
        {name: fieldTP, mapping: fieldTP, sortType: 'asUCString'},
        {name: fieldTOP, mapping: fieldTOP, sortType: 'asFloat'},
        {name: fieldLotSize, mapping: fieldLotSize, sortType: 'asInt'},
        {name: fieldCurrency, mapping: fieldCurrency, sortType: 'asUCString'},
        {name: fieldRemark, mapping: fieldRemark, sortType: 'asUCString'},
        {name: fieldPI, mapping: fieldPI, sortType: 'asUCString'},
        {name: fieldRD, mapping: fieldRD, sortType: 'asUCString'},
        {name: fieldExchangeCode, mapping: fieldExchangeCode, sortType: 'asUCString'},
        {name: 'margin', mapping: 'margin', sortType: 'asUCString'},
        {name: 'marginPrc', mapping: 'marginPrc', sortType: 'asFloat'},
        {name: 'marginPc', mapping: 'marginPc', sortType: 'asFloat'},
        {name: fieldValue, mapping: fieldValue, sortType: 'asInt'},
        {name: fieldIndexCode, mapping: fieldIndexCode, sortType: 'asInt'},
        //OSK
        {name: fieldExpiryDate, mapping: fieldExpiryDate, sortType: 'asDate'},
        {name: fieldExercisePrice, mapping: fieldExercisePrice, sortType: 'asFloat'},
        {name: fieldExerciseRatio, mapping: fieldExerciseRatio, sortType: 'asFloat'},
        {name: fieldGearingX, mapping: fieldGearingX, sortType: 'asFloat'},
        {name: fieldPremiumPerc, mapping: fieldPremiumPerc, sortType: 'asFloat'},
        {name: fieldImpVolatility, mapping: fieldImpVolatility, sortType: 'asFloat'},
        {name: fieldUnderlying, mapping: fieldUnderlying, sortType: 'asFloat'},
        {name: fieldOptionType, mapping: fieldOptionType, sortType: 'asUCString'},
        {name: fieldOptionStyle, mapping: fieldOptionStyle, sortType: 'asUCString'},
        //msgtype06
        {name: field52WHigh_06, mapping: field52WHigh_06, sortType: 'asFloat'},
        {name: field52WLow_06, mapping: field52WLow_06, sortType: 'asFloat'},
        {name: fieldIndexGrp_06, mapping: fieldIndexGrp_06, sortType: 'asUCString'},
        {name: fieldPrevStkNo_06, mapping: fieldPrevStkNo_06, sortType: 'asUCString'},
        {name: fieldPrevLongName_06, mapping: fieldPrevLongName_06, sortType: 'asUCString'},
        {name: fieldTickSize_06, mapping: fieldTickSize_06, sortType: 'asFloat'},
        {name: fieldTheoPrice_06, mapping: fieldTheoPrice_06, sortType: 'asFloat'},
        {name: fieldDynamicLow_06, mapping: fieldDynamicLow_06, sortType: 'asFloat'},
        {name: fieldDynamicHigh_06, mapping: fieldDynamicHigh_06, sortType: 'asFloat'},
        {name: fieldIssuer_06, mapping: fieldIssuer_06, sortType: 'asUCString'},
        {name: fieldUnderCurr_06, mapping: fieldUnderCurr_06, sortType: 'asUCString'},
        {name: fieldUnderName_06, mapping: fieldUnderName_06, sortType: 'asUCString'},
        //PSE
        {name: fieldFloatLevel_06, mapping: fieldFloatLevel_06, sortType: 'asFloat'},
        {name: fieldFreeFloat_06, mapping: fieldFreeFloat_06, sortType: 'asFloat'},
        {name: fieldFloatShare_06, mapping: fieldFloatShare_06, sortType: 'asFloat'},
        {name: fieldFlunctuation_06, mapping: fieldFlunctuation_06, sortType: 'asFloat'},
        {name: fieldForeignOwnerLimit, mapping: fieldForeignOwnerLimit, sortType: 'asFloat'},
        {name: fieldShrIssue, mapping: fieldShrIssue, sortType: 'asInt'},
        //Dividend Info
        {name: fieldEPS, mapping: fieldEPS, sortType: 'asFloat'},
        {name: fieldPERatio, mapping: fieldPERatio, sortType: 'asFloat'},
        {name: field12MDiv, mapping: field12MDiv, sortType: 'asFloat'},
        {name: fieldDivPay, mapping: fieldDivPay, sortType: 'asInt'},
        {name: fieldDivEx, mapping: fieldDivEx, sortType: 'asInt'},
        {name: fieldDivYld, mapping: fieldDivYld, sortType: 'asFloat'},
        {name: fieldDivCcy, mapping: fieldDivCcy, sortType: 'asUCString'},
        {name: fieldIntDiv, mapping: fieldIntDiv, sortType: 'asFloat'},
        {name: fieldIntExDate, mapping: fieldIntExDate, sortType: 'asInt'},
        {name: fieldSpDiv, mapping: fieldSpDiv, sortType: 'asFloat'},
        {name: fieldSpDivExDate, mapping: fieldSpDivExDate, sortType: 'asInt'},
        {name: fieldFinDiv, mapping: fieldFinDiv, sortType: 'asFloat'},
        {name: fieldFinDivExDate, mapping: fieldFinDivExDate, sortType: 'asInt'},
        {name: fieldFXSpread, 			mapping: fieldFXSpread,				sortType: 'asFloat'},
        //CIMBSG Circuit Breaker Enhancements
        {name: fieldRefPrice_06, mapping: fieldRefPrice_06, sortType: 'asFloat'},
        {name: fieldEndTime_06, 		mapping: fieldEndTime_06,			sortType: 'asUCString'},
        //CFD Columns
        {name: fieldCFDMapValue_06, 	mapping: fieldCFDMapValue_06,			sortType: 'asUCString'},
        {name: fieldCFDTradable_06, 	mapping: fieldCFDTradable_06,			sortType: 'asUCString'},
        {name: fieldCFDShortSell_06, 	mapping: fieldCFDShortSell_06,			sortType: 'asUCString'},
        {name: fieldCFDMarginPerc_06, 	mapping: fieldCFDMarginPerc_06,			sortType: 'asUCString'},
        {name: fieldCFDMarginLS_06, 	mapping: fieldCFDMarginLS_06,			sortType: 'asUCString'}
    ],
    proxy: {
        type: 'memory',
        reader: {
            type: 'json',
            rootProperty: 'data',
            totalProperty: 'count',
            successProperty: "success"
        }
    },
    idProperty: fieldStkCode
});