constQcAck=Welcome to the Trader Server

constUserParam=[UserParam]
constSenderName=[SenderName]
constKeepAlive=[PushTimeOut]
constSenderCode=[SenderCode]
constBranchCode=[BranchCode]
constSenderCategory=[SenderCategory]
constBrokerCode=[BrokerCode]
constAction=[Action]
constOrderType=[OrderType]
constValidity=[Validity]
constPayment=[Payment]
constCurrency=[Currency]
constCurrencyRate=[CurrencyRate]
constOthersCurrencyRate=[OthersCurrencyRate]
constRevise=[Revise]
constReviseOT=[ReviseOT]
constReviseV=[ReviseV]
constOrderControl=[OrderCtrl2]
constReviseControl=[ReviseCtrl]
constIniControl=[IniCtrl]
constExchange=[Exchange]
constPublicIp=[PublicIP]
constPrivateIp=[PrivateIP]
constIsOutBoundActivated=[IsOutBoundActivated]
constMobileNo=[Mobile]
constEmail=[Email]


const2FARequired=[Is2FARequired]
const2FADeviceList=[DeviceList]
const2FABypass=[2FAByPass]
const2FAMobPhone=[2FAMobPhone]
const2FASMSOTPInt=[2FASMSOTPInterval]

constLocalExchange=[LocalExchange]
constRDSStatus=[RDSStatus]
constRDSVersion=[RDSVersion]

constTrxFeeFormula=[TrxFeeFormula]

constMapPaymentCode=[MapPaymentCode]
constPFEntryExchange=[PFEntryExchange]
constPFEntryAccType=[PFEntryAccType]

constTPType=[TriggerPriceType]
constTPDirection=[TriggerPriceDirection]

constResetPwdPIN=[ResetPwdPin]
constPymtCurrency=[PaymentCurrency]
constPaymentConfig=[PaymentCfg_Payment]
constNotSupportedCurr=[CurrencyNotSupported]
constBidSize=[BidSize]

constPegOffsetType=[OffsetType]
constTakeProfitOrdType=[TakeProfitOrdType]
constStopLossOrdType=[StopLossOrdType]
constCloseCondOrdCtrl=[CloseCondOrdCtrl]

constHomeCurrency=[HomeCurrency]
constIDSSEnabled=[IDSSEnabled]
constIDSSOption=[IDSSOption]

#1.3.24.5 [Add constSkipPin]
constSkipPin=[SkipPin]
constEND=[END]

constOMSID=[OMSID]

#constError=ERROR,
#constError500=Error 500
#constError502=Error 502
#constError509=Error 509
#constError510=Error 510
#constError513=Error 513
#constError514=Error 514
#constHttp=HTTP/1.1
#constReqAck=HTTP/1.1 200 OK
#constReqAck500=HTTP/1.1 500
#constReqAck502=HTTP/1.1 502
#constReqAck509=HTTP/1.1 509
#constReqAck510=HTTP/1.1 510
#constReqAck513=HTTP/1.1 513
#constReqAck514=HTTP/1.1 514
#constReqAck401=HTTP/1.1 401
#HTTP/1.1 401 1100 ATP - Invalid session (header)
#Error 401  1100 ATP - Invalid session (body)
constErr1100ATP=1100 ATP
constErr1201ATP=1201 ATP

#Max retry on sending hb to atp
#[Default]: 3
constMaxATPhbCounter=3

constBoundary=boundary=
constContentType=Content-Type:
constContentLength=Content-Length:
constInvalidSession=Invalid session
constSessionTimeout=Session time out
constServerBusy=Server object is busy
constOrdStatus=OrdStatus
constATPOrdStsTimeFmt=yyyyMMddHHmmss.SSS
constMSLOrdStsTimeFmt=HH:mm:ss
constMSLOrdStsDateFmt=yyyy-MM-dd

# Application Code to let ATP know when perform trading (buy / sell / cancel / revise)
# this is for ATP check is tclite, phone or tcPro
constATPAppCodeValue=LP

#cliSetting [constTCLSetting is main name to search in ATP+OMS otherwise is individual name for the features]
constTCLSetting=TCL
constMMColSetting=TCLMMCOLS
constWLColSetting=TCLWLCOLS
constScreenSize=TCLRESSIZ
constOSColSetting=TCLOSCOLS
constOHColSetting=TCLOHCOLS
constMFOHColSetting=TCLMFOHCOLS
constPFColSetting=TCLPFCOLS
constPFREALColSetting=TCLRGLCOLS
constPesonalizationThemeSetting=TCLPTHEME
constFontSetting=TCLFS
constTradeDefaultAccount=TCLTDA
constTradeAccountOrder=TCLTAO
constMDColSetting=TCLMDCOLS
constMDSetting=TCLMDSET
#constMainLayout=TCLML
#constTbMainLayout=TCLTBML
constMainLayout=TCLMLV2
constTbMainLayout=TCLTBML
constTbMainLayoutV2=TCLTLV2
constMbMainLayout=TCLMBML

# layout profile 1
constUserLayoutA1=TCLULA1
constUserLayoutB1=TCLULB1
constUserLayoutC1=TCLULC1
constUserLayoutD1=TCLULD1
constUserLayoutE1=TCLULE1
constUserLayoutF1=TCLULF1
constUserLayoutG1=TCLULG1
constUserLayoutH1=TCLULH1
constUserLayoutI1=TCLULI1
constUserLayoutJ1=TCLULJ1
constUserLayoutK1=TCLULK1
constUserLayoutL1=TCLULL1
constUserLayoutM1=TCLULM1
constUserLayoutN1=TCLULN1
constUserLayoutO1=TCLULO1
constUserLayoutP1=TCLULP1
constUserLayoutQ1=TCLULQ1
constUserLayoutR1=TCLULR1
constUserLayoutZ1=TCLULZ1
# layout profile 2
constUserLayoutA2=TCLULA2
constUserLayoutB2=TCLULB2
constUserLayoutC2=TCLULC2
constUserLayoutD2=TCLULD2
constUserLayoutE2=TCLULE2
constUserLayoutF2=TCLULF2
constUserLayoutG2=TCLULG2
constUserLayoutH2=TCLULH2
constUserLayoutI2=TCLULI2
constUserLayoutJ2=TCLULJ2
constUserLayoutK2=TCLULK2
constUserLayoutL2=TCLULL2
constUserLayoutM2=TCLULM2
constUserLayoutN2=TCLULN2
constUserLayoutO2=TCLULO2
constUserLayoutP2=TCLULP2
constUserLayoutQ2=TCLULQ2
constUserLayoutR2=TCLULR2
constUserLayoutZ2=TCLULZ2
# layout profile 3
constUserLayoutA3=TCLULA3
constUserLayoutB3=TCLULB3
constUserLayoutC3=TCLULC3
constUserLayoutD3=TCLULD3
constUserLayoutE3=TCLULE3
constUserLayoutF3=TCLULF3
constUserLayoutG3=TCLULG3
constUserLayoutH3=TCLULH3
constUserLayoutI3=TCLULI3
constUserLayoutJ3=TCLULJ3
constUserLayoutK3=TCLULK3
constUserLayoutL3=TCLULL3
constUserLayoutM3=TCLULM3
constUserLayoutN3=TCLULN3
constUserLayoutO3=TCLULO3
constUserLayoutP3=TCLULP3
constUserLayoutQ3=TCLULQ3
constUserLayoutR3=TCLULR3
constUserLayoutZ3=TCLULZ3
# layout profile 4
constUserLayoutA4=TCLULA4
constUserLayoutB4=TCLULB4
constUserLayoutC4=TCLULC4
constUserLayoutD4=TCLULD4
constUserLayoutE4=TCLULE4
constUserLayoutF4=TCLULF4
constUserLayoutG4=TCLULG4
constUserLayoutH4=TCLULH4
constUserLayoutI4=TCLULI4
constUserLayoutJ4=TCLULJ4
constUserLayoutK4=TCLULK4
constUserLayoutL4=TCLULL4
constUserLayoutM4=TCLULM4
constUserLayoutN4=TCLULN4
constUserLayoutO4=TCLULO4
constUserLayoutP4=TCLULP4
constUserLayoutQ4=TCLULQ4
constUserLayoutR4=TCLULR4
constUserLayoutZ4=TCLULZ4
# layout profile 5
constUserLayoutA5=TCLULA5
constUserLayoutB5=TCLULB5
constUserLayoutC5=TCLULC5
constUserLayoutD5=TCLULD5
constUserLayoutE5=TCLULE5
constUserLayoutF5=TCLULF5
constUserLayoutG5=TCLULG5
constUserLayoutH5=TCLULH5
constUserLayoutI5=TCLULI5
constUserLayoutJ5=TCLULJ5
constUserLayoutK5=TCLULK5
constUserLayoutL5=TCLULL5
constUserLayoutM5=TCLULM5
constUserLayoutN5=TCLULN5
constUserLayoutO5=TCLULO5
constUserLayoutP5=TCLULP5
constUserLayoutQ5=TCLULQ5
constUserLayoutR5=TCLULR5
constUserLayoutZ5=TCLULZ5

constMappedNames=TCLMN
constMbMappedNames=TCLMBMN
constTbMappedNames=TCLTMN
constTickerSettingItems=TCLTSI
constFontSizeSetting=TCLFSSET
constUserPreference=TCLUPRF
constLayoutPreference=TCLLPRF
constLayoutCol1=TCLPCOL1
constLayoutCol2=TCLPCOL2
constLayoutCol3=TCLPCOL3
constLayoutCol4=TCLPCOL4
constLayoutCol5=TCLPCOL5
constLayoutColM=TCLPCOLM
constRecentQuote=TCLRQL
constHotKeysMapping=TCLHKM
constSyncComp=TCLSCG
constCalculatorPreference=TCLTCAL
constMutualFundPreference=TCLMFUND
constSettingPreference=TCLSRPF
#mobile settings#
constMbMMColSetting=TCLMBMMCOL
constMbWLColSetting=TCLMBWLCOL
constMbPFColSetting=TCLMBPFCOL
constMbPFREALColSetting=TCLMBRGLC
constMbOSColSetting=TCLMBOSCOL
constStockAlert=TCLALERT
constDMSetting=TCLDMSET

### column width: desktop ###
constColWidthQuoteKL=TCLQSKL
constColWidthQuoteKLL=TCLQSKLL
constColWidthQuoteMY=TCLQSMY
constColWidthQuoteSG=TCLQSSG
constColWidthQuoteSI=TCLQSSI
constColWidthQuoteHC=TCLQSHC
constColWidthQuoteHN=TCLQSHN
constColWidthQuoteUP=TCLQSUP
constColWidthQuoteJK=TCLQSJK
constColWidthQuoteHK=TCLQSHK
constColWidthQuoteA=TCLQSA
constColWidthQuoteN=TCLQSN
constColWidthQuoteO=TCLQSO
constColWidthQuoteP=TCLQSP
constColWidthQuotePH=TCLQSPH
constColWidthQuoteBK=TCLQSBK

constColWidthQuoteSA=TCLQSSA
constColWidthQuoteOM=TCLQSOM
constColWidthQuoteYM=TCLQSYM
constColWidthQuoteES=TCLQSES
constColWidthQuoteZS=TCLQSZS
constColWidthQuoteUC=TCLQSUC
constColWidthQuoteAX=TCLQSAX
constColWidthQuoteL=TCLQSL
constColWidthQuoteENG=TCLQSENG
constColWidthQuoteMT=TCLQSMT
constColWidthQuoteWIDX=TCLQSWIDX
constColWidthQuoteT=TCLQST

constColWidthWatchlist=TCLWL
constColWidthRecentQuote=TCLRQ

constColWidthMfOrderStatus=TCLMFOS
constColWidthOrderStatus=TCLOS
constColWidthOrderHistory=TCLOH
constColWidthMFOrderHistory=TCLMFOH
constColWidthBasketOrder=TCLBO

constColWidthEquityPrtf=TCLEP
constColWidthEquityPrtfRP=TCLRP
constColWidthFundPrtf=TCLFP

constColWidthTrackerTS=TCLTRTS
constColWidthTrackerBS=TCLTRBS
constColWidthScoreboard=TCLSB
constColWidthDerivativeSummary=TCLDPSM
constColWidthCFDHolding=TCLCFD
constColWidthMutualFund=TCLMF

### column width: mobile ###
constMbColWidthQuoteKL=TCLMQSKL
constMbColWidthQuoteKLL=TCLMQSKLL
constMbColWidthQuoteMY=TCLMQSMY
constMbColWidthQuoteSG=TCLMQSSG
constMbColWidthQuoteSI=TCLMQSSI
constMbColWidthQuoteHC=TCLMQSHC
constMbColWidthQuoteHN=TCLMQSHN
constMbColWidthQuoteUP=TCLMQSUP
constMbColWidthQuoteJK=TCLMQSJK
constMbColWidthQuoteHK=TCLMQSHK
constMbColWidthQuoteA=TCLMQSA
constMbColWidthQuoteN=TCLMQSN
constMbColWidthQuoteO=TCLMQSO
constMbColWidthQuoteP=TCLMQSP
constMbColWidthQuotePH=TCLMQSPH
constMbColWidthQuoteBK=TCLMQSBK

constMbColWidthQuoteSA=TCLMQSSA
constMbColWidthQuoteOM=TCLMQSOM
constMbColWidthQuoteYM=TCLMQSYM
constMbColWidthQuoteES=TCLMQSES
constMbColWidthQuoteZS=TCLMQSZS
constMbColWidthQuoteUC=TCLMQSUC
constMbColWidthQuoteAX=TCLMQSAX
constMbColWidthQuoteL=TCLMQSL
constMbColWidthQuoteENG=TCLMQSENG
constMbColWidthQuoteMT=TCLMQSMT
constMbColWidthQuoteWIDX=TCLMQSWIDX
constMbColWidthQuoteT=TCLMQST

constMbColWidthWatchlist=TCLMWL
constMbColWidthRecentQuote=TCLMRQ

constMbColWidthMFOrderStatus=TCLMMFOS
constMbColWidthOrderStatus=TCLMOS
constMbColWidthOrderHistory=TCLMOH
constMbColWidthMFOrderHistory=TCLMMFOH

constMbColWidthEquityPrtf=TCLMEP
constMbColWidthEquityPrtfRP=TCLMRP

constMbColWidthTrackerTS=TCLMTRTS
constMbColWidthTrackerBS=TCLMTRBS
constMbColWidthScoreboard=TCLMSB
constMbColWidthDerivativeSummary=TCLMDPSM
constMbColWidthCFDHolding=TCLMCFD
constMbColWidthMutualFund=TCLMMF

#mapping [DY 20120104 - will ignore all the information take from ATP]
constPaymentVal=Cash|CPF|CPF.B-|CPF.I|SRS
constPaymentDesc=Cash|CPF|CPF.B-|CPF.I|SRS

funcSession=main.connectionManager.notifySession
funcAccount=main.connectionManager.updateAccount
funcInvalidAck=main.connectionManager.notifyInvalidAck
funcChgPwd=main.connectionManager.updateChangePwdResult
funcChgPin=main.connectionManager.updateChangePinResult
funcPortfolio=main.connectionManager.updatePortfolio
funcPrtfSumm=main.connectionManager.updatePrtfSumm
funcOrderStatus=main.connectionManager.updateOrdSts
funcOrdStsSumm=main.connectionManager.updateOrdStsSumm
funcOrderDetail=main.connectionManager.updateOrderDetail
funcTrade=main.connectionManager.updateTradeResult
funcCancelOrder=main.connectionManager.updateCancelOrderStatus
funcReviseOrder=main.connectionManager.updateReviseOrderStatus
funcVirtualPL=main.connectionManager.updatePortfolio
funcDerivPrtf=main.connectionManager.updatePortfolio
funcLogout=main.connectionManager.updateUnknown

reqFavourite=Favorate
importWatchlist=TradeImportWatchlist
reqTradeTicket=TradeTicket
reqCreateBasket=CreateBasket
reqDeleteBasket=DeleteBasket
reqGetAllBasket=GetAllBasket
reqUpdateBasketInfo=UpdateBasketInfo
reqGetBasketItems=GetOrdInfoByBskID
reqSaveBasketItems=UpdateOrdIntoBasket

# only configure one Currency (either it allow support multiple) 
confDefaultCurrency_N2N=MYR
confDefaultCurrency_UTRADE=PHP
confDefaultCurrency_AMFRASER=SGD
confDefaultCurrency_AMFUTURE=MYR
confDefaultCurrency_IF=MYR
confDefaultCurrency_HDBS=MYR
confDefaultCurrency_TA=MYR
confDefaultCurrency_AIBB=MYR
confDefaultCurrency_AMSEC=MYR
confDefaultCurrency_HDCAP=IDR
confDefaultCurrency_INTERPAC=MYR
confDefaultCurrency_KIBB=MYR
confDefaultCurrency_MNA=MYR
confDefaultCurrency_PSE=PHP

confDefaultPayment_N2N=Cash
confDefaultPayment_UTRADE=Cash
confDefaultPayment_AMFRASER=Cash
confDefaultPayment_AMFUTURE=Cash
confDefaultPayment_IF=Cash
confDefaultPayment_HDBS=Cash
confDefaultPayment_TA=Cash
confDefaultPayment_AIBB=Cash
confDefaultPayment_AMSEC=Cash
confDefaultPayment_HDCAP=Cash
confDefaultPayment_INTERPAC=Cash
confDefaultPayment_KIBB=Cash
confDefaultPayment_MNA=Cash
confDefaultPayment_PSE=

# 2011-12-30 [added - skipconfm|forceord|forcequeue]
# 2013-10-04 [added - bts2features(enable trigger price type & trigger price direction)(for KL only)]
confOrderFieldMeta=ex|contra|force|amalgamation|payment|settcurr|minqty|stoplimit|shortsell|dsqty|strategy|showlimit|skipconfm|forceord|forcequeue|bts2features|triggertype|triggerdirection|privateOrd|ordertype|stkqty|stkprice|validity
#ex|contra|force|amalgamation|payment|settcurr|minqty|stoplimit|shortsell|dsqty|trdparty|showlimit
confOrderFieldValue_N2N=KL|N|N|N|N|N|N|N|N|N|N|Y|N|N|N
#confOrderFieldValue_UTRADE=KL|N|N|N|N|Y|N|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,MY|N|N|N|Y|Y|Y|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,HKD|N|N|N|N|Y|Y|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,HK|N|N|N|N|Y|Y|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,A|N|N|N|N|Y|Y|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,O|N|N|N|N|Y|Y|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,N|N|N|N|N|Y|Y|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,JK|N|N|N|N|Y|Y|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,BK|N|N|N|N|Y|Y|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,SG|N|N|N|N|Y|Y|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,PH|N|N|N|N|Y|N|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,HC|N|N|N|N|Y|Y|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N,HN|N|N|N|N|Y|Y|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N
confOrderFieldValue_UTRADE=PH|N|N|N|N|Y|N|Y|N|Y|N|Y|Y|N|N|Y|Y|Y|N|Y|Y|Y|Y
confOrderFieldValue_AMFRASER=SG|N|N|N|Y|Y|Y|Y|Y|Y|N|Y|Y|N|N
confOrderFieldValue_AMFUTURE=MY|N|N|N|N|N|Y|Y|N|Y|N|N|N|N|N
confOrderFieldValue_IF=MY|N|N|N|N|N|Y|Y|N|Y|N|N|N|N|N
confOrderFieldValue_HDBS=KL|N|N|N|N|N|N|N|N|N|N|Y|N|N|N,MY|N|N|N|N|N|Y|Y|N|Y|N|N|N|N|N
confOrderFieldValue_TA=KL|N|N|N|N|N|N|N|N|N|N|Y|N|N|N
confOrderFieldValue_AIBB=KL|N|N|N|N|N|N|N|N|N|N|Y|N|N|N
confOrderFieldValue_AMSEC=KL|N|N|N|N|N|N|N|N|N|N|Y|N|N|N
confOrderFieldValue_HDCAP=JK|N|N|N|Y|Y|Y|Y|N|Y|N|Y|Y|N|N
confOrderFieldValue_INTERPAC=KL|N|N|N|N|N|N|N|N|N|N|Y|N|N|N
confOrderFieldValue_KIBB=KL|N|N|N|N|N|N|N|N|N|N|Y|N|N|N
confOrderFieldValue_MNA=KL|N|N|N|Y|Y|Y|Y|N|Y|N|Y|Y|N|N
confOrderFieldValue_PSE=PH|N|N|N|N|Y|Y|Y|N|Y|N|Y|Y|N|N

confOrderFieldMetaMF=ex|skipconfm|settcurr|netcashlimit|amount|mfqty
confOrderFieldValueMF_UTRADE=PHMF|Y|Y|Y|Y|Y

confDefaultOrderFieldMeta=contract|qty|dsqty|stoplimit|minqty
confOrderDefaultFieldValue_UTRADE=
confOrderDefaultFieldValue_TA=1||||

confOrderExMapping_N2N=
confOrderExMapping_UTRADE=SID=SI|HKD=HK|AD=A|ND=N|OD=O
confOrderExMapping_AMFRASER=
confOrderExMapping_AMFUTURE=
confOrderExMapping_IF=
confOrderExMapping_HDBS=
confOrderExMapping_TA=
confOrderExMapping_AIBB=
confOrderExMapping_AMSEC=
confOrderExMapping_HDCAP=
confOrderExMapping_INTERPAC=
confOrderExMapping_KIBB=
confOrderExMapping_MNA=
confOrderExMapping_PSE=

confBlockSenderCategory_N2N=
confBlockSenderCategory_UTRADE=
confBlockSenderCategory_AMFRASER=D|R
confBlockSenderCategory_AMFUTURE=
confBlockSenderCategory_IF=
confBlockSenderCategory_HDBS=
confBlockSenderCategory_TA=
confBlockSenderCategory_AIBB=
confBlockSenderCategory_AMSEC=
confBlockSenderCategory_HDCAP=
confBlockSenderCategory_INTERPAC=
confBlockSenderCategory_KIBB=
confBlockSenderCategory_MNA=
confBlockSenderCategory_PSE=


# trade conditions (bitwise) - GC - copy from CalcFunc - get from tcweb
#constTCStkInsufficient=8;
#constTCLimitExceed=256;
#constTCOddLot=512;
#constTCExceedBids=1024;
#constTCContra=8192;
#constTCSplitOrd=16384;
#constTCAmalgamate=16;
#constTCForceKey=32;
#constTCShortSell=262144;
#constTCSIP1=2048;
#constTCSIP2=4096;
