BrokerGetWLAPI=tcplus/watchlist?action=get&id=<ID>&wl=<WLName>&o=<TimeStamp>
BrokerAddWLAPI=tcplus/watchlist?action=add&id=<ID>&wl=<WLName>&key=<Key>&o=<TimeStamp>
BrokerRemWLAPI=tcplus/watchlist?action=rem&id=<ID>&wl=<WLName>&key=<Key>&o=<TimeStamp>
BrokerCreWLAPI=tcplus/watchlist?action=create&id=<ID>&wl=<WLName>&o=<TimeStamp>
BrokerDelWLAPI=tcplus/watchlist?action=del&id=<ID>&wl=<WLName>&o=<TimeStamp>
BrokerRenameWLAPI=tcplus/watchlist?action=rename&id=<ID>&nwl=<NewWLName>&wl=<OldWLName>&o=<TimeStamp>

BrokerInitAPI=GET /TradeGetSession HTTP/1.1
BrokerE2EEAPI=GET /TradeGetE2EEParams HTTP/1.1
BrokerLoginAPI=GET /[<LoginKey>]TradeLogin?Username=<LoginID>|Password=<Password>|PullMode=<PullMode>|AppName=<AppName>|Language=EN|Compress=<CompressMode>|EncryptedUP=<EncryptMode>|Encryption=0|PullCompress=<PullCompress> HTTP/1.1
BrokerLoginICAPI=GET /[<LoginKey>]TradeLogin?Username=<LoginID>|PullMode=<PullMode>|AppName=<AppName>|Language=EN|Compress=<CompressMode>|EncryptedUP=<EncryptMode>|Encryption=0|PullCompress=<PullCompress>|ICPNo=<ICPNo>|AppCode=<AppCode> HTTP/1.1 


#BrokerBuySellAPI=GET /[<UserParam>]TradeTicket?*=<UUID>|2=<SenderCode>|3=<BrokerCode>|/=<ClientCode>|.=<AccNo>|4=<Action>|5=<StockCode>|7=<Date>|;=<Qty>|8=I|M=<BranchCode>|P=<Exchange>|R=<PIN>|<APP_CODE>=<APP_CODE_VALUE><CONDITIONAL> HTTP/1.1
#BrokerCanRevAPI=GET /[<UserParam>]TradeTicket?*=<UUID>|+=<OrderNo>|,=<SuborderNo>|.=<AccNo>|/=<ClientCode>|2=<SenderCode>|3=<BrokerCode>|4=<Action>|5=<StockCode>|7=<Date>|8=I|:=<ExpiredDate>|;=<Qty>|D=<UnmatchQty>|E=<MatchedQty>|M=<BranchCode>|P=<Exchange>|R=<PIN>|<APP_CODE>=<APP_CODE_VALUE><CONDITIONAL> HTTP/1.1
BrokerBuySellAPI=Request=<CONDITIONAL>|&UserParams=<UserParam>
BrokerCanRevAPI=Request=<CONDITIONAL>|&UserParams=<UserParam>
BrokerRevAPI=GET /[<UserParam>]TradeTicket?*=<UUID>|+=<OrderNo>|,=<SuborderNo>|.=<AccNo>|/=<ClientCode>|2=<SenderCode>|3=<BrokerCode>|4=<Action>|5=<StockCode>|7=<Date>|8=I|:=<ExpiredDate>|;=<Qty>|D=<UnmatchQty>|E=<MatchedQty>|M=<BranchCode>|P=<Exchange>|R=<PIN>|<APP_CODE>=<APP_CODE_VALUE><CONDITIONAL> HTTP/1.1

BrokerOrdStsAPI=GET /[<UserParam>]TradeStatus?'=<SenderCode><CONDITIONAL> HTTP/1.1

BrokerDerivativePrtfInfoAPI=GET /[<UserParam>]TradePrtfSummRpt?.=<ClientAcc>|3=<BrokerCode>|M=<BranchCode>|Z=<Unrealized> HTTP/1.1
BrokerDerivativePrtfAPI=GET /[<UserParam>]TradePrtfSubDtlRpt?.=<ClientAcc>|3=<BrokerCode>|M=<BranchCode>|Z=<Unrealized>|+=<StockCode>|b=<Exchange> HTTP/1.1
BrokerDerivativePrtfDetailAPI=GET /[<UserParam>]TradePrtfDtlRpt?.=<ClientAcc>|3=<BrokerCode>|M=<BranchCode>|Z=<Unrealized>|+=<StockCode>|b=<Exchange>|c=<AccExchangeCode>|g=<Mode> HTTP/1.1

BrokerPrtfAPI=GET /[<UserParam>]TradePortfolio?'=<SenderCode>|.=<AccNo>|3=<BrokerCode>|M=<BranchCode>|Z=<PORTFOLIO_TYPE>|b=<Exchange>|g=<Category>|d=<StkExchange> HTTP/1.1
#BrokerPrtfDetailAPI=GET /[<UserParam>]GetPortfolioDt?+=<SenderCode>|2=<AccNo>|,=<BrokerCode>|-=<BranchCode>|.=<PORTFOLIO_TYPE>|/=<Exchange>|0=<Exchange>|3=<Exchange> HTTP/1.1
BrokerPrtfDetailAPI=GET /[<UserParam>]GetPortfolioDt?+=<Clicode>|2=<BHCliCode>|,=<StockCode>|-=<Side>|.=<PageNo>|/=<NumberRow>|0=<BHCode>|3=<BHBranch>|8=<Category><CONDITIONAL> HTTP/1.1
BrokerPrtfDetailUpdateAPI=GET /[<UserParam>]EditPortfolioDt?+=<DocumentNo>|,=<DocumentSqNo>|-=<Quantity>|/=<Price>|0=<TransFee>|3=<OrderSource>|5=<Category> HTTP/1.1
BrokerPrtfDetailAddAPI=GET /[<UserParam>]AddPortfolio?+=<ExchangeRefNo>|,=<ExchangeSeqNo>|-=<CDSNo>|.=<BHClicode>|/=<BHCode>|0=<BHBranch>|1=<Exchange>|2=<AccExchange>|3=<StkCode>|4=<Side>|5=<Quantity>|6=<Price>|7=<Remark>|8=<OrderSource>|9=<TransFee>|<=<Category>|?=<SettMode> HTTP/1.1
BrokerPrtfDetailDeleteAPI=GET /[<UserParam>]DelPortfolio?+=<OrderNo>|,=<SubOrderNo>|-=<Side>|.=<ExchangeCode>|1=<Category> HTTP/1.1


BrokerAccAPI=GET /[<UserParam>]TradeClient?'=<SenderCode> HTTP/1.1
BrokerSearchAccAPI=GET /[<UserParam>]TradeClientFind?'=<SenderCode>|U=BHClicode|V=<SearchValue>|S=<PageNo>|T=<TotalRec> HTTP/1.1
BrokerChgPINAPI=GET /[<UserParam>]TradeChgPIN?'=<SenderCode>|*=<LoginID>|-=<OldPIN>|.=<NewPIN> HTTP/1.1
BrokerChgPwdAPI=GET /[<UserParam>]TradeChgPasswd?'=<SenderCode>|*=<LoginID>|+=<OldPassword>|,=<NewPassword> HTTP/1.1
BrokerConnectAPI=GET /[<UserParam>]TradeConnect?~=<PullMode>|'=<SenderCode> HTTP/1.1
BrokerAliveAPI=GET /[<UserParam>]TradeAlive?o=<TimeStamp> HTTP/1.1
BrokerCheckSingleLogonAPI=GET /[<UserParam>]CheckSingleLogon?+=<userName> HTTP/1.1
BrokerCreditLimitAPI=GET /[<UserParam>]TradeClientLimit?'=<SenderCode>|.=<AccNo>|/=<ClientCode>|3=<BrokerCode>|M=<BranchCode>|P=<Exchange><CONDITIONAL> HTTP/1.1
BrokerLogoutAPI=GET /[<UserParam>]TradeLogout HTTP/1.1
BrokerPrtfSubDtlAPI=GET /[<UserParam>]TradePrtfSubDtlRpt?.=<AccNo> HTTP/1.1
BrokerPrtfDtlAPI=GET /[<UserParam>]TradePrtfDtlRpt?.=<AccNo> HTTP/1.1
BrokerPrtfSummAPI=GET /[<UserParam>]TradePrtfSummRpt?.=<AccNo> HTTP/1.1
BrokerOrdHistoryAPI=GET /[<UserParam>]TradeHistory?'=<SenderCode>|.=<AccNo>|3=<BrokerCode>|M=<BranchCode>|P=<Exchange>|[=<StsHistory>|^=<FromDate>|_=<ToDate><CONDITIONAL> HTTP/1.1
BrokerOrdLogAPI=GET /[<UserParam>]TradeLog?+=<OrderNo>|,=<SuborderNo>|/=<ClientCode>|[=<StsHistory>|^=<FromDate>|_=<ToDate> HTTP/1.1
BrokerGetCliSetting=GET /[<UserParam>]ClientSetting?*=GetCliSetting|,=<ClientCode>|0=<ServiceCode>|>=1 HTTP/1.1
BrokerSaveCliSetting=Request=*=SaveCliSetting|,=<ClientCode>|0=<ServiceCode>|3=<Params>&UserParams=<UserParam>
BrokerGetFavAPI=GET /[<UserParam>]Favorate?*=GetFavListInfo|+=<ClientCode>|,=1 HTTP/1.1
BrokerDelFavAPI=GET /[<UserParam>]Favorate?*=DelFavList|+=<ClientCode>|4=1|-=<FavID> HTTP/1.1
BrokerUpdFavAPI=GET /[<UserParam>]Favorate?*=UpdFavListName|+=<ClientCode>|-=<FavID>|.=<FavName>|/=0|0=AC2B9B1AB3654898A049E153A06F5AF80.8621339868992101 HTTP/1.1
BrokerGetFavStkAPI=GET /[<UserParam>]Favorate?*=GetFavListStkCodeCache|+=<ClientCode>|-=<FavID> HTTP/1.1
BrokerUpdFavStkAPI=GET /[<UserParam>]Favorate?*=UpdFavListStk|+=<ClientCode>|-=<FavID>|.=<FavName>|/=0|0=AC2B9B1AB3654898A049E153A06F5AF80.8621339868992101|1=<StockCode>|2=<Exchange> HTTP/1.1
BorkerDelFavStkAPI=GET /[<UserParam>]Favorate?*=DelFavListStk|+=<ClientCode>|-=<FavID>|1=<StockCode>|2=<Exchange> HTTP/1.1
BorkerChkDblLoginAPI=GET /[<UserParam>]Favorate?*=DelFavListStk|+=<ClientCode>|-=<FavID>|1=<StockCode>|2=<Exchange> HTTP/1.1

Broker2FAValidation=GET /[<UserParam>]ValidateOTP?'=<ClientCode>|+=<DeviceID>|,=<OTPValue>|/=<ICNumber>|1=<DevType><CONDITIONAL> HTTP/1.1
Broker1FAValidation=GET /[<UserParam>]ValidateOneFA?+=<UserID>|,=<UserPassword>|-=<E2EEPassword>|.=<Challenge> HTTP/1.1

BrokerRDSValidation=GET /[<UserParam>]UpdateRDSStatus?+=<ExCliCode>|,=<BHCliCode>|-=<BHCode>|.=<BHBranch>|/=<AccExchCode>|0=<RDSStatus>|1=<RDSVersion>|2=<RDSType>|5=<Application> HTTP/1.1

BrokerAccepTCAPI=GET /[<UserParam>]AcceptESOSTNC?+=<ClientCode>|,=<PF_NO>|-=<ESOS_BATCH_NO>  HTTP/1.1
BrokerForgotPinAPI=GET /[<ADMIN>]TradeForgetPIN?*=<PF_NO>|-=<IC_NO>|,=|.=0  HTTP/1.1

BrokerPostHeader=POST /<Function> HTTP/1.1\r\n\
Content-Type: application/x-www-form-urlencoded\r\n\
Host: <Host>\r\n\
Content-Length: <ContentLength>\r\n\r\n

BrokerUpdFavPostAPI=Request=*=UpdFavListName|+=<ClientCode>|-=<FavID>|.=<FavName>|/=0|0=AC2B9B1AB3654898A049E153A06F5AF80.8621339868992101&UserParams=<UserParam>
BrokerUpdFavStkPostAPI=Request*=UpdFavListStk|+=<ClientCode>|-=<FavID>|.=<FavName>|/=0|1=<StockCode>|2=<Exchange>|0=AC2B9B1AB3654898A049E153A06F5AF80.8621339868992101&UserParams=<UserParam>

#BrokerImportWlAPI=GET /[<UserParam>]TradeImportWatchlist?+=<ClientCode>|-=<FavID>|.=<FavName>|6=<StkList> HTTP/1.1
BrokerImportWlAPI=Request=+=<ClientCode>|-=<FavID>|.=<FavName>|6=<StkList>&UserParams=<UserParam>
BrokerCUTGetFXTrxListAPI=GET /[<UserParam>]CUTGetFXTrxList?'=<SenderCode>|+=<AccNo>|,=<BrokerCode>|-=<BranchCode>|2=<Exchange><CONDITIONAL> HTTP/1.1
BrokerCUTCashBalanceAPI=GET /[<UserParam>]CUTCashBalance?'=<SenderCode>|+=<AccNo>|,=<BrokerCode>|-=<BranchCode>|.=<Exchange>|<CONDITIONAL> HTTP/1.1

BrokerCreateBasketAPI=Request='=<SenderCode>|+=<BasketName>|&UserParams=<UserParam>
BrokerDeleteBasketAPI=Request='=<SenderCode>|,=<BasketId>|&UserParams=<UserParam>
BrokerGetAllBasketAPI=Request='=<SenderCode>|&UserParams=<UserParam>
BrokerUpdateBasketInfoAPI=Request=<CONDITIONAL>|&UserParams=<UserParam>
BrokerGetBasketItemsAPI=Request='=<SenderCode>|,=<BasketId>|&UserParams=<UserParam>
BrokerSaveBasketItemsAPI=Request='=<SenderCode>|,=<BasketId>|0=<BasketItems>|&UserParams=<UserParam>

#move to N2NConstant.properties param LMSSubAuthen
#LMSSubAuthen=http://lms-cimbuat.asiaebroker.com/lmscimbtemp/websub/authen?identifier=<LoginID>&sponsor=<SponsorID>&prod=Trader%20Connect%20Lite
