SORT_VOL=16
SORT_GAINER=13
SORT_LOSER=13
SORT_GAINERP=14
SORT_LOSERP=14
SORT_SYMBOL=2
SORT_TOTALTRADE=18
SORT_TOTALVALUE=17
SORT_CLOSE=4
ASC_VOL=1
ASC_GAINER=1
ASC_LOSER=0
ASC_GAINERP=1
ASC_LOSERP=0
ASC_SYMBOL=0
ASC_TOTALTRADE=1
ASC_TOTALVALUE=1
ASC_CLOSE=1


KL_COUNTRY=60
KL_EXCHGID=01
MY_COUNTRY=60
MY_EXCHGID=02
SG_COUNTRY=65
SG_EXCHGID=01
SA_COUNTRY=966
SA_EXCHGID=01
OM_COUNTRY=968
OM_EXCHGID=01


