# To change this template, choose Tools | Templates
# and open the template in the editor.

feedStockHistoricalChart=http://chart.asiaebroker.com/chart/historical?d=<Day>&k=<Key>&w=<Width>&h=<Height>&o=<TimeStamp><OPT>
feedStockAnalysisChart=http://chart.asiaebroker.com/chart/analysis?d=<Day>&k=<Key>&w=<Width>&h=<Height>&o=<TimeStamp>&dp=<DayParams>&t=<Type><OPT>
feedStockCombineAnalysisChart=http://chart.asiaebroker.com/chart/combineanalysis?d=<Day>&k=<Key>&w=<Width>&h=<Height>&o=<TimeStamp>&dp=<DayParams>&t=<Type><OPT>
feedStockIntradayChart=http://chart.asiaebroker.com/chart/intraday?k=<Key>&w=<Width>&h=<Height>&o=<TimeStamp><OPT>
